import { Team } from "./LeagueTable.type";

export const LEAGUE_TABLE_HEADERS = [
  "Position",
  "Club",
  "Matches played",
  "Wins",
  "Draws",
  "Losses",
  "Goals scored",
  "Goals against",
  "Goal difference",
  "Points",
  "Last 5",
];

export const TEAMS: Team[] = [
  {
    position: 1,
    club: "Liverpool",
    logo: "/club-logos/Liverpool.png",
    matchesPlayed: 25,
    wins: 18,
    draws: 6,
    losses: 1,
    goalsScored: 60,
    goalsAgainst: 24,
    goalDifference: 36,
    points: 60,
    last5: ["Win", "Win", "Win", "Draw", "Win"],
  },
  {
    position: 2,
    club: "Arsenal",
    logo: "/club-logos/Arsenal.png",
    matchesPlayed: 25,
    wins: 15,
    draws: 8,
    losses: 2,
    goalsScored: 51,
    goalsAgainst: 22,
    goalDifference: 29,
    points: 53,
    last5: ["Win", "Draw", "Win", "Win", "Win"],
  },
  {
    position: 3,
    club: "Nottm Forest",
    logo: "/club-logos/Nottingham-Forest.png",
    matchesPlayed: 25,
    wins: 14,
    draws: 5,
    losses: 6,
    goalsScored: 41,
    goalsAgainst: 29,
    goalDifference: 12,
    points: 47,
    last5: ["Draw", "Win", "Loss", "Win", "Loss"],
  },
  {
    position: 4,
    club: "Man City",
    logo: "/club-logos/Manchester-City.png",
    matchesPlayed: 25,
    wins: 13,
    draws: 5,
    losses: 7,
    goalsScored: 52,
    goalsAgainst: 35,
    goalDifference: 17,
    points: 44,
    last5: ["Draw", "Win", "Win", "Loss", "Win"],
  },
  {
    position: 5,
    club: "Bournemouth",
    logo: "/club-logos/Bournemouth.png",
    matchesPlayed: 25,
    wins: 12,
    draws: 7,
    losses: 6,
    goalsScored: 44,
    goalsAgainst: 29,
    goalDifference: 15,
    points: 43,
    last5: ["Draw", "Win", "Win", "Loss", "Win"],
  },
  {
    position: 6,
    club: "Chelsea",
    logo: "/club-logos/Chelsea.png",
    matchesPlayed: 25,
    wins: 12,
    draws: 7,
    losses: 6,
    goalsScored: 47,
    goalsAgainst: 34,
    goalDifference: 13,
    points: 43,
    last5: ["Draw", "Win", "Loss", "Win", "Loss"],
  },
  {
    position: 7,
    club: "Newcastle",
    logo: "/club-logos/Newcastle-United.png",
    matchesPlayed: 25,
    wins: 12,
    draws: 5,
    losses: 8,
    goalsScored: 42,
    goalsAgainst: 33,
    goalDifference: 9,
    points: 41,
    last5: ["Win", "Loss", "Win", "Loss", "Loss"],
  },
  {
    position: 8,
    club: "Fulham",
    logo: "/club-logos/Fulham.png",
    matchesPlayed: 25,
    wins: 10,
    draws: 9,
    losses: 6,
    goalsScored: 38,
    goalsAgainst: 33,
    goalDifference: 5,
    points: 39,
    last5: ["Loss", "Win", "Loss", "Win", "Win"],
  },
  {
    position: 9,
    club: "Aston Villa",
    logo: "/club-logos/Aston-Villa.png",
    matchesPlayed: 25,
    wins: 10,
    draws: 8,
    losses: 7,
    goalsScored: 35,
    goalsAgainst: 38,
    goalDifference: -3,
    points: 38,
    last5: ["Win", "Draw", "Draw", "Loss", "Draw"],
  },
  {
    position: 10,
    club: "Brighton",
    logo: "/club-logos/Brighton.png",
    matchesPlayed: 25,
    wins: 9,
    draws: 10,
    losses: 6,
    goalsScored: 38,
    goalsAgainst: 38,
    goalDifference: 0,
    points: 37,
    last5: ["Win", "Win", "Loss", "Loss", "Win"],
  },
  {
    position: 11,
    club: "Brentford",
    logo: "/club-logos/Brentford.png",
    matchesPlayed: 25,
    wins: 10,
    draws: 4,
    losses: 11,
    goalsScored: 43,
    goalsAgainst: 42,
    goalDifference: 1,
    points: 34,
    last5: ["Draw", "Loss", "Win", "Loss", "Win"],
  },
  {
    position: 12,
    club: "Tottenham",
    logo: "/club-logos/Tottenham.png",
    matchesPlayed: 25,
    wins: 9,
    draws: 3,
    losses: 13,
    goalsScored: 49,
    goalsAgainst: 37,
    goalDifference: 12,
    points: 30,
    last5: ["Loss", "Loss", "Loss", "Win", "Win"],
  },
  {
    position: 13,
    club: "Crystal Palace",
    logo: "/club-logos/Crystal-Palace.png",
    matchesPlayed: 25,
    wins: 7,
    draws: 9,
    losses: 9,
    goalsScored: 29,
    goalsAgainst: 32,
    goalDifference: -3,
    points: 30,
    last5: ["Win", "Win", "Loss", "Win", "Loss"],
  },
  {
    position: 14,
    club: "Everton",
    logo: "/club-logos/Everton.png",
    matchesPlayed: 25,
    wins: 7,
    draws: 9,
    losses: 9,
    goalsScored: 27,
    goalsAgainst: 31,
    goalDifference: -4,
    points: 30,
    last5: ["Win", "Win", "Win", "Draw", "Win"],
  },
  {
    position: 15,
    club: "Man United",
    logo: "/club-logos/Manchester-United.png",
    matchesPlayed: 25,
    wins: 8,
    draws: 5,
    losses: 12,
    goalsScored: 28,
    goalsAgainst: 35,
    goalDifference: -7,
    points: 29,
    last5: ["Win", "Loss", "Win", "Loss", "Loss"],
  },
  {
    position: 16,
    club: "West Ham",
    logo: "/club-logos/West-Ham.png",
    matchesPlayed: 25,
    wins: 7,
    draws: 6,
    losses: 12,
    goalsScored: 29,
    goalsAgainst: 47,
    goalDifference: -18,
    points: 27,
    last5: ["Win", "Loss", "Draw", "Loss", "Loss"],
  },
  {
    position: 17,
    club: "Wolves",
    logo: "/club-logos/Wolves.png",
    matchesPlayed: 25,
    wins: 5,
    draws: 4,
    losses: 16,
    goalsScored: 35,
    goalsAgainst: 54,
    goalDifference: -19,
    points: 19,
    last5: ["Loss", "Loss", "Loss", "Win", "Loss"],
  },
  {
    position: 18,
    club: "Ipswich Town",
    logo: "/club-logos/Ipswich-Town.png",
    matchesPlayed: 25,
    wins: 3,
    draws: 8,
    losses: 14,
    goalsScored: 23,
    goalsAgainst: 50,
    goalDifference: -27,
    points: 17,
    last5: ["Loss", "Loss", "Loss", "Loss", "Draw"],
  },
  {
    position: 19,
    club: "Leicester City",
    logo: "/club-logos/Leicester-City.png",
    matchesPlayed: 25,
    wins: 4,
    draws: 5,
    losses: 16,
    goalsScored: 25,
    goalsAgainst: 55,
    goalDifference: -30,
    points: 17,
    last5: ["Loss", "Loss", "Win", "Loss", "Loss"],
  },
  {
    position: 20,
    club: "Southampton",
    logo: "/club-logos/Southampton.png",
    matchesPlayed: 25,
    wins: 2,
    draws: 3,
    losses: 20,
    goalsScored: 19,
    goalsAgainst: 57,
    goalDifference: -38,
    points: 9,
    last5: ["Loss", "Loss", "Loss", "Win", "Loss"],
  },
];
